import Foundation

public enum HealthFacts {
    public struct Fact {
        public let ru: String
        public let en: String

        public func text(lang: String) -> String {
            lang == "ru" ? ru : en
        }
    }

    public static let facts: [Fact] = [
        Fact(ru: "В теле человека более 650 мышц.",
             en: "There are over 650 muscles in the human body."),
        Fact(ru: "Сердце — тоже мышца, и оно бьется всё время, даже когда вы отдыхаете.",
             en: "The heart is also a muscle, and it never stops beating, even when you're resting."),
        Fact(ru: "Мышцы могут только сокращаться (тянуть); они не могут самостоятельно выталкивать нагрузку.",
             en: "Muscles can only contract (pull); they cannot push weight on their own."),
        Fact(ru: "Улыбка тренирует мышцы лица и поднимает настроение.",
             en: "Smiling uses muscles in your face and improves your mood."),
        Fact(ru: "Во время смеха укрепляются мышцы живота, ведь дыхание становится более глубоким и ритмичным.",
             en: "When you laugh, your abdominal muscles get a workout because your breathing becomes deeper and rhythmic."),
        Fact(ru: "Тренировка помогает телу сжигать калории даже после окончания занятий.",
             en: "Working out helps your body burn calories even after the exercise is over."),
        Fact(ru: "Если вы сделали перерыв в тренировках, мышцам будет легче вернуться в форму из-за мышечной памяти.",
             en: "If you take a break from exercise, your muscles will find it easier to get back in shape later because of muscle memory."),
        Fact(ru: "Плавание задействует почти все основные группы мышц и бережет суставы.",
             en: "Swimming engages almost all major muscle groups and is gentle on the joints."),
        Fact(ru: "Лучшая зарядка для мышц — регулярные короткие тренировки, чем редкие но длительные.",
             en: "The best workout for your muscles is short, regular sessions rather than rare long ones."),
        Fact(ru: "Спустя пару часов после тренировки мышцы растут в ходе отдыха, поэтому важен качественный сон.",
             en: "Muscles grow a few hours after a workout during rest, so getting good sleep is important."),
        Fact(ru: "Силовые упражнения повышают метаболизм: вы тратите больше калорий даже после окончания тренировки.",
             en: "Strength exercises boost metabolism: you burn more calories even after the workout is over."),
        Fact(ru: "Легкая дрожь в мышцах после занятий — это нормально, мышцы распознают нагрузку и растут.",
             en: "A slight muscle tremor after exercise is normal — your muscles recognize the load and get stronger."),
        Fact(ru: "Когда мышцы работают, они выделяют тепло, поэтому на тренировке вам становится жарче.",
             en: "When your muscles work, they generate heat, which is why you feel warmer when you exercise."),
        Fact(ru: "Чтобы мышцы были сильными, нужно правильно питаться: они «строятся» из белка и нуждаются в витаминах.",
             en: "To have strong muscles, you need proper nutrition: muscles are \"built\" from protein and need vitamins."),
        Fact(ru: "Сердце работает сильнее, чем мышцы ног даже у самого тренированного бегуна.",
             en: "The heart works harder than even the strongest runner’s leg muscles."),
        Fact(ru: "Сердце бьется более 100 тысяч раз в день.",
             en: "The heart beats over 100,000 times a day."),
        Fact(ru: "Сердце перекачивает около 7 литров крови каждую минуту, это примерно 10 тонн за день.",
             en: "The heart pumps about 7 liters of blood every minute, which is around 10 tons in a day."),
        Fact(ru: "Кровеносные сосуды во всем теле вместе могли бы обмотать Землю дважды.",
             en: "All the blood vessels in your body, laid end to end, could circle the Earth twice."),
        Fact(ru: "Регулярные кардио-тренировки укрепляют сердце и снижают риск сердечных болезней.",
             en: "Regular cardio workouts strengthen the heart and reduce the risk of heart disease."),
        Fact(ru: "Смех расслабляет кровеносные сосуды, и сердцу становится легче качать кровь.",
             en: "Laughter relaxes your blood vessels and makes it easier for your heart to pump blood."),
        Fact(ru: "У спортсменов пульс в покое обычно ниже — это признак более сильного сердца.",
             en: "Athletes usually have a lower resting heart rate — that’s a sign of a stronger heart."),
        Fact(ru: "Когда вы двигаетесь, сердце ускоряется — чтобы отправить больше кислорода мышцам.",
             en: "When you move, your heart rate goes up — to send more oxygen to your muscles."),
        Fact(ru: "Сердце имеет два отдела: правый направляет кровь в легкие, а левый — по всему телу.",
             en: "The heart has two sides: the right sends blood to the lungs, the left to the rest of the body."),
        Fact(ru: "Поднимайтесь по лестнице — это тренировка для ног и стимул для сердца.",
             en: "Walking up stairs is a workout for your legs and a boost for your heart."),
        Fact(ru: "Новые кроссовки могут вдохновить на тренировку: когда вещи крутые, хочется двигаться.",
             en: "New sneakers can inspire you to work out: when your gear is cool, you want to move."),
        Fact(ru: "Спортсмены часто лучше спят: уставшее тело быстро засыпает и восстанавливается во сне.",
             en: "Athletes often sleep better: a tired body falls asleep and recovers quickly."),
        Fact(ru: "Смех помогает тратить калории: 15 минут смеха сжигают около 10–40 калорий.",
             en: "Laughing helps burn calories: 15 minutes of laughter can burn about 10–40 calories."),
        Fact(ru: "Зимой не забывайте согреться: разогрев тела перед бегом на холоде снижает риск травм.",
             en: "In winter, don’t forget to warm up: warming your body before running in the cold reduces injury risk."),
        Fact(ru: "Хорошая осанка помогает легким работать лучше — вы дышите полнее.",
             en: "Good posture helps your lungs work better — you breathe more fully."),
        Fact(ru: "Во время бега старайтесь дышать ровно: это дает больше кислорода мышцам.",
             en: "When running, try to breathe steadily: it gives more oxygen to your muscles."),
        Fact(ru: "Секрет выносливости — регулярность: лучше заниматься понемногу, но часто.",
             en: "The secret to endurance is regularity: it’s better to exercise a little often than rarely."),
        Fact(ru: "Если устали, контрастный душ снимет усталость и придаст сил.",
             en: "If you’re tired, a contrast shower (hot and cold) will relieve fatigue and give you energy."),
        Fact(ru: "Наш организм примерно на 60% состоит из воды — не забывайте пить регулярно.",
             en: "About 60% of your body is water — don’t forget to drink regularly."),
        Fact(ru: "Каждый раз, как вы потеете, теряете воду — пейте до и после тренировки.",
             en: "Every time you sweat, you lose water — drink before and after your workout."),
        Fact(ru: "Всего 2% потери воды заставляют вас быстрее устать на тренировке.",
             en: "Losing just 2% of your body water makes you get tired faster during exercise."),
        Fact(ru: "Питьевая вода улучшает перенос питательных веществ к мышцам.",
             en: "Drinking water improves the delivery of nutrients to your muscles."),
        Fact(ru: "Молоко после силовой тренировки восстанавливает мышцы благодаря белку и кальцию.",
             en: "Milk after strength training helps muscles recover thanks to its protein and calcium."),
        Fact(ru: "Вода в овощах, фруктах и супе входит в вашу ежедневную норму жидкости.",
             en: "The water in vegetables, fruits, and soup counts toward your daily fluid intake."),
        Fact(ru: "Не заменяйте воду сладкими напитками: они не утоляют жажду так хорошо.",
             en: "Don’t replace water with sugary drinks: they don’t quench thirst as well."),
        Fact(ru: "Пейте воду маленькими глотками в течение дня — так легче поддерживать гидратацию.",
             en: "Drink water in small sips throughout the day — it’s easier to maintain hydration that way."),
        Fact(ru: "В жаркую погоду вы теряете больше воды — не забывайте пить, даже если не чувствуете жажду.",
             en: "In hot weather you lose more water — keep drinking even if you don’t feel thirsty."),
        Fact(ru: "Пейте и перед тренировкой, и во время, и после — так ваше тело будет в лучшем тонусе.",
             en: "Drink before, during, and after your workout — that way your body will stay in better shape."),
        Fact(ru: "Хороший ужин перед утренней тренировкой предотвращает слабость и обмороки.",
             en: "A good dinner before a morning workout prevents weakness and fainting."),
        Fact(ru: "Не ешьте тяжелую пищу прямо перед тренировкой — выберите лёгкий перекус.",
             en: "Don’t eat a heavy meal just before a workout — opt for a light snack instead."),
        Fact(ru: "Белок после тренировки важен: он помогает мышцам восстановиться.",
             en: "Protein after a workout is important: it helps your muscles recover."),
        Fact(ru: "Банан перед тренировкой дает быстрый заряд энергии и калий для мышц.",
             en: "A banana before a workout gives you a quick energy boost and potassium for your muscles."),
        Fact(ru: "Овсянка на завтрак даёт энергию надолго благодаря сложным углеводам.",
             en: "Oatmeal for breakfast gives you long-lasting energy thanks to complex carbs."),
        Fact(ru: "Салат с овощами обеспечивает организм витаминами и помогает восстановлению.",
             en: "A salad with vegetables provides your body with vitamins and helps with recovery."),
        Fact(ru: "Шоколадное молоко после тренировки восстанавливает мышцы и возвращает энергию.",
             en: "Chocolate milk after a workout restores your muscles and gives you back energy."),
        Fact(ru: "Спорт требует отдыха: мышцы растут и укрепляются во время отдыха, а не во время самой тренировки.",
             en: "Exercise requires rest: muscles grow and strengthen during rest, not during the workout itself."),
        Fact(ru: "Недосып мешает прогрессу: без сна мышцы не успевают восстановиться.",
             en: "Lack of sleep hinders progress: without sleep, your muscles don’t have time to recover."),
        Fact(ru: "Дайте себе выходной между интенсивными тренировками — это тоже часть тренинга.",
             en: "Give yourself a day off between intense workouts — that’s part of the training too."),
        Fact(ru: "Правильная разминка усиливает кровоток и уменьшает риск растяжений.",
             en: "Proper warm-up increases blood flow and reduces the risk of strains."),
        Fact(ru: "Перед прыжками и бегом сделайте несколько разминочных шагов и растяжек.",
             en: "Before jumps and running, do some warm-up steps and stretches."),
        Fact(ru: "Если что-то болит сильно, лучше прерваться — так вы предупредите более серьезную травму.",
             en: "If something hurts badly, it’s better to stop — this way you prevent a more serious injury."),
        Fact(ru: "Легкая растяжка после занятий делает мышцы более гибкими и уменьшает крепатуру.",
             en: "Gentle stretching after exercise makes muscles more flexible and reduces soreness."),
        Fact(ru: "После интенсивной тренировки немного походите — это поможет быстрее восстановиться.",
             en: "After an intense workout, walk around a bit — it helps you recover faster."),
        Fact(ru: "Контрастный душ (горячая-холодная вода) тренирует сосуды и борется с усталостью.",
             en: "A contrast shower (hot and cold water) trains your blood vessels and fights fatigue."),
        Fact(ru: "Во время сна укрепляется иммунитет и мышцы — не пренебрегайте отдыхом.",
             en: "During sleep, your immune system and muscles strengthen — don’t neglect rest."),
        Fact(ru: "Массаж или валик для самомассажа облегчают боль в мышцах на следующий день.",
             en: "A massage or foam roller helps relieve muscle pain the next day."),
        Fact(ru: "Поддерживайте правильную осанку: ровная спина бережет ваш позвоночник.",
             en: "Maintain good posture: a straight back protects your spine."),
        Fact(ru: "При ходьбе смотрите вперед, а не вниз — так лучше держите равновесие.",
             en: "When walking, look forward, not down — this helps you maintain better balance."),
        Fact(ru: "Носите рюкзак на обоих плечах — вашим костям это нравится.",
             en: "Wear your backpack on both shoulders — your bones will like it."),
        Fact(ru: "Стоя прямо, представляйте, что макушка тянется к потолку: это выпрямляет позвоночник.",
             en: "Stand up straight and imagine the top of your head reaching toward the ceiling: it straightens your spine."),
        Fact(ru: "При приседаниях держите спину прямо, колени не выходят далеко вперед.",
             en: "When squatting, keep your back straight and don’t let your knees go too far forward."),
        Fact(ru: "Смех полезен для тела и души — он поднимает настроение и расслабляет мышцы лица.",
             en: "Laughter is good for body and soul — it lifts your mood and relaxes your facial muscles."),
        Fact(ru: "Не игнорируйте боль: она сигнализирует о возможной травме.",
             en: "Don’t ignore pain: it signals a possible injury."),
        Fact(ru: "При травме приложите лед на 10–15 минут — это поможет уменьшить отек.",
             en: "If you're injured, apply ice for 10–15 minutes — it helps reduce swelling."),
        Fact(ru: "Правильная обувь с хорошей поддержкой снижает риск растяжений и болей в спине.",
             en: "Proper shoes with good support reduce the risk of sprains and back pain."),
        Fact(ru: "Не увлекайтесь одним видом нагрузки: сочетайте кардио, силовые и растяжку.",
             en: "Don’t do just one type of exercise: combine cardio, strength training, and stretching."),
        Fact(ru: "Правильная техника всех упражнений обязательна — так вы избежите травм.",
             en: "Proper technique in all exercises is a must — it helps you avoid injuries."),
        Fact(ru: "Если вам не хватает воздуха во время бега, значит темп слишком высок — замедлитесь.",
             en: "If you're out of breath during a run, you're going too fast — slow down."),
        Fact(ru: "Держите пресс в тонусе: он поддерживает позвоночник и помогает сохранять хорошую осанку.",
             en: "Keep your abs toned: they support your spine and help you maintain good posture."),
        Fact(ru: "Чтобы избежать перегрузки, делайте хотя бы один день отдыха между тяжелыми тренировками.",
             en: "To avoid overtraining, take at least one rest day between heavy workouts."),
        Fact(ru: "Регулярная физическая активность повышает иммунитет — будете реже болеть.",
             en: "Regular physical activity boosts your immune system — you’ll get sick less often."),
        Fact(ru: "Найдите вид спорта, который вам нравится — тогда тренироваться будет в радость.",
             en: "Find a sport you enjoy — then exercising will be a pleasure."),
        Fact(ru: "Ставьте небольшие цели: например, сегодня пробежал 1 км, завтра — 1.5 км.",
             en: "Set small goals: for example, run 1 km today, 1.5 km tomorrow."),
        Fact(ru: "Любимая музыка повышает мотивацию и помогает держать темп.",
             en: "Your favorite music boosts motivation and helps you keep pace."),
        Fact(ru: "Поддержка друзей облегчает тренировки: вместе веселее и продуктивнее.",
             en: "Support from friends makes workouts easier: it’s more fun and productive together."),
        Fact(ru: "Не переживайте, если пропустили тренировку — просто продолжайте дальше.",
             en: "Don’t worry if you miss a workout — just continue on."),
        Fact(ru: "Награждайте себя за достижения: новая футболка или полезное лакомство мотивируют.",
             en: "Reward yourself for achievements: a new T-shirt or a healthy treat motivates you."),
        Fact(ru: "Не бойтесь ошибок: они помогают учиться новому.",
             en: "Don’t be afraid of mistakes: they help you learn new things."),
        Fact(ru: "Вести дневник тренировок интересно — вы видите прогресс и гордитесь достигнутым.",
             en: "Keeping a workout journal is fun — you see your progress and feel proud of what you’ve done."),
        Fact(ru: "Чихание со скоростью до 160 км/ч разгоняет воздух — проверено на практике!",
             en: "A sneeze travels up to 160 km/h — trust the science!"),
        Fact(ru: "Занимаясь спортом на свежем воздухе, вы получаете заряд энергии и витамин D от солнца.",
             en: "Exercising outdoors gives you an energy boost and vitamin D from the sun."),
        Fact(ru: "Детям нужно около часа активности в день, а взрослым — не менее 150 минут в неделю.",
             en: "Children need about one hour of activity per day, and adults at least 150 minutes per week."),
        Fact(ru: "Подъем тяжестей укрепляет не только мышцы, но и кости.",
             en: "Lifting weights strengthens not just muscles, but also bones."),
        Fact(ru: "Физическая активность заставляет мозг выделять эндорфины — они улучшают настроение.",
             en: "Physical activity makes your brain release endorphins — they improve your mood."),
        Fact(ru: "Спорт помогает социализироваться: в зале можно найти новых друзей и единомышленников.",
             en: "Sports help you socialize: you can find new friends and like-minded people at the gym."),
        Fact(ru: "Йога сочетает гибкость, силу и умение расслабляться.",
             en: "Yoga combines flexibility, strength, and the ability to relax."),
        Fact(ru: "Быстрая ходьба тоже считается тренировкой — даже прогулка на свежем воздухе полезна.",
             en: "Brisk walking counts as exercise too — even a walk outdoors is beneficial."),
        Fact(ru: "Мышцы лица задействуются даже когда вы жуёте жвачку или разговариваете.",
             en: "Facial muscles are engaged even when you chew gum or talk."),
        Fact(ru: "Зимой теплоотдача происходит быстрее: тёплая одежда помогает избежать простуды.",
             en: "In winter, your body loses heat faster: wearing warm clothes helps prevent colds."),
        Fact(ru: "Если вы долго стоите, слегка сгибайте колени — так нагрузка на спину будет меньше.",
             en: "If you stand for a long time, keep your knees slightly bent — this puts less strain on your back."),
        Fact(ru: "Каждый шаг ходящего человека — это небольшая тренировка для ног.",
             en: "Every step of someone walking is a small workout for the legs."),
        Fact(ru: "Если после тренировки вы полны энергии, это нормально: вы выделили «гормоны счастья».",
             en: "If you feel energetic after a workout — that’s normal: you released ‘happiness hormones’."),
        Fact(ru: "В жару лучше тренироваться рано утром или вечером — тогда вам будет не так жарко.",
             en: "In hot weather, it’s better to train early morning or evening — it won’t feel as hot."),
        Fact(ru: "Маленькие упражнения в течение дня помогают оставаться в форме: не ждите, пока всё свободное время будет для спорта.",
             en: "Small exercises during the day help keep you fit — don’t wait until all your free time is for sports."),
        Fact(ru: "Даже уборка дома сжигает калории и держит мышцы в тонусе.",
             en: "Even cleaning the house burns calories and keeps your muscles in tone."),
        Fact(ru: "Меняйте упражнения каждый месяц, чтобы мышцы не привыкали к нагрузке.",
             en: "Change your exercises every month so your muscles don’t get used to the load."),
        Fact(ru: "Не пропускайте разминку, думая, что сэкономите время — это обойдётся дороже.",
             en: "Don’t skip a warm-up thinking you’ll save time — it will cost you more."),
        Fact(ru: "Учтите, что вода есть не только в воде — фрукты и супы тоже увлажняют.",
             en: "Remember that you get water not only from beverages — fruits and soups hydrate you too."),
        Fact(ru: "Человеческая мышца укрепляется быстрее при частых, но коротких занятиях.",
             en: "The human muscle gets stronger faster with frequent but short workouts."),
        Fact(ru: "Один марафон в год лучше, чем месяц на диване.",
             en: "One marathon a year is better than spending a month on the couch."),
        Fact(ru: "В спортзале люди обычно сосредоточены на своих целях — не стесняйтесь быть частью этого.",
             en: "People in the gym are usually focused on their goals — don’t hesitate to be a part of it."),
        Fact(ru: "Зимние виды спорта (лыжи, коньки) развивают мышцы ног особенно хорошо.",
             en: "Winter sports (skiing, skating) develop your leg muscles especially well."),
        Fact(ru: "Круговые движения плечами улучшают кровообращение в верхней части тела.",
             en: "Circular shoulder movements improve circulation in your upper body."),
        Fact(ru: "Любая активность лучше бездействия — например, стояние тоже укрепляет выносливость.",
             en: "Any activity is better than inactivity — for example, standing also builds endurance."),
        Fact(ru: "Заучивайте технику упражнений по проверенным источникам, а не по случайным видео.",
             en: "Learn exercise techniques from reliable sources, not just from random videos."),
        Fact(ru: "Представляйте цель перед тренировкой — психологически так настроиться проще.",
             en: "Visualize your goal before a workout — it’s easier to get in the right mindset that way."),
        Fact(ru: "Даже когда болит спина, лёгкая зарядка иногда улучшает самочувствие.",
             en: "Even when your back hurts, a light workout can sometimes make you feel better."),
        Fact(ru: "Тренировки утром делают вас бодрее — так сон и спорт дополняют друг друга.",
             en: "Working out in the morning makes you more energetic — it’s like sleep and exercise complement each other."),
        Fact(ru: "Не нужен спортзал, чтобы быть активным: работайте головой и ногами — телом вообще.",
             en: "You don’t need a gym to be active: work with your head, your legs — with your whole body."),
        Fact(ru: "Иногда полезно сделать пять берпи прямо сейчас: мышцы будут благодарны за всплеск активности.",
             en: "Sometimes it’s useful to do five burpees right now: your muscles will thank you for the burst of activity."),
        Fact(ru: "Если тренировка кажется скучной, включите музыку или подкаст — время пролетит незаметно.",
             en: "If a workout seems boring, play some music or a podcast — time will fly by."),
        Fact(ru: "В дождь идите заниматься под дождём или найдите дома упражнение: движение полезно в любую погоду.",
             en: "On a rainy day, exercise in the rain or find a home workout: moving is good in any weather."),
        Fact(ru: "Заканчивайте тренировку лёгким растягиванием — мышцы будут менее жёсткими на утро.",
             en: "Finish your workout with a light stretch — your muscles will be less stiff in the morning."),
        Fact(ru: "Спортивное питание — это не магия, реальную пользу даёт обычная здоровая еда.",
             en: "Sports nutrition is not magic; real benefits come from normal healthy food."),
        Fact(ru: "Не гонитесь за рекордами слишком часто: каждая тренировка — шаг к новой цели.",
             en: "Don’t chase records too often: each workout is a step towards a new goal."),
        Fact(ru: "Лёгкая активность утром улучшает работу мозга на весь день.",
             en: "Even light activity in the morning sharpens your brain for the whole day."),
        Fact(ru: "Следите за техникой упражнений — правильно сделанное упражнение помогает избежать травм.",
             en: "Watch your exercise technique — doing an exercise correctly helps you avoid injuries."),
        Fact(ru: "Самоконтроль в спорте развивает силу воли в обычной жизни.",
             en: "Self-control in sports builds willpower in everyday life."),
        Fact(ru: "Человеку легче переносить жару, чем холод: одевайтесь теплее и двигайтесь, чтобы согреться.",
             en: "Humans endure heat better than cold: dress warmly and move to stay warm."),
        Fact(ru: "Регулярные занятия спортом делают вас позитивнее: взгляд на жизнь становится оптимистичнее.",
             en: "Regular exercise makes you more positive: you’ll have a more optimistic outlook on life."),
        Fact(ru: "Не делайте тяжёлую тренировку два дня подряд — чередуйте нагрузку.",
             en: "Don’t do a heavy workout two days in a row — alternate intensity."),
        Fact(ru: "Порой отдых восстанавливает лучше, чем дополнительная тренировка.",
             en: "Sometimes rest recovers you better than an extra workout."),
        Fact(ru: "Даже умственные игры разгоняют кровь: дайте мозгу тоже немного попотеть.",
             en: "Even brain games get the blood flowing: give your brain a workout too."),
        Fact(ru: "Если надоело стоять, сделайте выпады на месте — это тоже нагрузка.",
             en: "If you’re tired of standing, do lunges in place — it’s still a workout."),
        Fact(ru: "Играйте с друзьями на свежем воздухе: это и движение, и веселье одновременно.",
             en: "Play outdoor games with friends: it’s both exercise and fun at the same time."),
        Fact(ru: "Быстро приближаться к пределу не нужно: постепенно и безопасно увеличивайте нагрузку.",
             en: "There’s no need to push too hard too fast: gradually and safely increase the intensity.")
    ]

    public static var factsRU: [String] {
        facts.map(\.ru)
    }

    public static var factsEN: [String] {
        facts.map(\.en)
    }

    public static func randomFact() -> Fact {
        facts.randomElement()
            ?? Fact(ru: "Движение помогает телу оставаться сильным.",
                    en: "Movement helps the body stay strong.")
    }

    public static func random(lang: String = "ru") -> String {
        randomFact().text(lang: lang)
    }
}
